
// This code has been generated by the C2W code generator.
// Do not edit manually!

package GLDTestFederation;

import java.util.HashSet;
import java.util.Set;

import hla.rti.*;

import c2w.hla.*;

/**
* The market class implements the market object in the
* GLDTestFederation simulation.
*/
public class market extends ObjectRoot {

	/**
	* Default constructor -- creates an instance of the market object
	* class with default attribute values.
	*/
	public market() { }

	
	
	private static int _market_id_handle;
	private static int _period_handle;
	private static int _unit_handle;
	
	
	/**
	* Returns the handle (RTI assigned) of the "market_id" attribute of
	* its containing object class.
	*
	* @return the handle (RTI assigned) of the "market_id" attribute
	*/
	public static int get_market_id_handle() { return _market_id_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "period" attribute of
	* its containing object class.
	*
	* @return the handle (RTI assigned) of the "period" attribute
	*/
	public static int get_period_handle() { return _period_handle; }
	
	/**
	* Returns the handle (RTI assigned) of the "unit" attribute of
	* its containing object class.
	*
	* @return the handle (RTI assigned) of the "unit" attribute
	*/
	public static int get_unit_handle() { return _unit_handle; }
	
	
	
	private static boolean _isInitialized = false;

	private static int _handle;

	/**
	* Returns the handle (RTI assigned) of the market object class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return the handle of the class pertaining to the reference,\
	* rather than the handle of the class for the instance referred to by the reference.
	* For the polymorphic version of this method, use {@link #getClassHandle()}.
	*/
	public static int get_handle() { return _handle; }

	/**
	* Returns the fully-qualified (dot-delimited) name of the market
	* object class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return the name of the class pertaining to the reference,\
	* rather than the name of the class for the instance referred to by the reference.
	* For the polymorphic version of this method, use {@link #getClassName()}.
	*/
	public static String get_class_name() { return "ObjectRoot.market"; }

	/**
	* Returns the simple name (the last name in the dot-delimited fully-qualified
	* class name) of the market object class.
	*/
	public static String get_simple_class_name() { return "market"; }

	private static Set< String > _datamemberNames = new HashSet< String >();
	private static Set< String > _allDatamemberNames = new HashSet< String >();

	/**
	* Returns a set containing the names of all of the non-hidden attributes in the
	* market object class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return a set of parameter names pertaining to the reference,\
	* rather than the parameter names of the class for the instance referred to by
	* the reference.  For the polymorphic version of this method, use
	* {@link #getAttributeNames()}.
	*/
	public static Set< String > get_attribute_names() {
		return new HashSet< String >( _datamemberNames );
	}


	/**
	* Returns a set containing the names of all of the attributes in the
	* market object class.
	* Note: As this is a static method, it is NOT polymorphic, and so, if called on
	* a reference will return a set of parameter names pertaining to the reference,\
	* rather than the parameter names of the class for the instance referred to by
	* the reference.  For the polymorphic version of this method, use
	* {@link #getAttributeNames()}.
	*/
	public static Set< String > get_all_attribute_names() {
		return new HashSet< String >( _allDatamemberNames );
	}


	
	private static AttributeHandleSet _publishedAttributeHandleSet;
	private static Set< String > _publishAttributeNameSet = new HashSet< String >();

	private static AttributeHandleSet _subscribedAttributeHandleSet; 
	private static Set< String > _subscribeAttributeNameSet = new HashSet< String >();

	

	static {
		_classNameSet.add( "ObjectRoot.market" );
		_classNameClassMap.put( "ObjectRoot.market", market.class );
		
		_datamemberClassNameSetMap.put( "ObjectRoot.market", _datamemberNames );
		_allDatamemberClassNameSetMap.put( "ObjectRoot.market", _allDatamemberNames );

		
		
		_datamemberNames.add( "market_id" );
		_datamemberNames.add( "period" );
		_datamemberNames.add( "unit" );
		
		
		_allDatamemberNames.add( "market_id" );
		_allDatamemberNames.add( "period" );
		_allDatamemberNames.add( "unit" );
		
		
		_datamemberTypeMap.put( "market_id", "long" );
		_datamemberTypeMap.put( "period", "int" );
		_datamemberTypeMap.put( "unit", "String" );
	

		_classNamePublishAttributeNameMap.put( "ObjectRoot.market", _publishAttributeNameSet );
		_publishedAttributeHandleSet = _factory.createAttributeHandleSet();
		_classNamePublishedAttributeMap.put( "ObjectRoot.market", _publishedAttributeHandleSet );

		_classNameSubscribeAttributeNameMap.put( "ObjectRoot.market", _subscribeAttributeNameSet );
		_subscribedAttributeHandleSet = _factory.createAttributeHandleSet();
		_classNameSubscribedAttributeMap.put( "ObjectRoot.market", _subscribedAttributeHandleSet );
	

	}


	private static String initErrorMessage = "Error:  ObjectRoot.market:  could not initialize:  ";
	protected static void init( RTIambassador rti ) {
		if ( _isInitialized ) return;
		_isInitialized = true;
		
		ObjectRoot.init( rti );
		
		boolean isNotInitialized = true;
		while( isNotInitialized ) {
			try {
				_handle = rti.getObjectClassHandle( "ObjectRoot.market" );
				isNotInitialized = false;
			} catch ( FederateNotExecutionMember f ) {
				System.err.println( initErrorMessage + "Federate Not Execution Member" );
				f.printStackTrace();
				return;				
			} catch ( NameNotFound n ) {
				System.err.println( initErrorMessage + "Name Not Found" );
				n.printStackTrace();
				return;				
			} catch ( Exception e ) {
				e.printStackTrace();
				try { Thread.sleep( 50 ); } catch( Exception e1 ) { }					
			}
		}

		_classNameHandleMap.put( "ObjectRoot.market", get_handle() );
		_classHandleNameMap.put( get_handle(), "ObjectRoot.market" );
		_classHandleSimpleNameMap.put( get_handle(), "market" );

		
		isNotInitialized = true;
		while( isNotInitialized ) {
			try {
							
				_market_id_handle = rti.getAttributeHandle( "market_id", get_handle() );			
				_period_handle = rti.getAttributeHandle( "period", get_handle() );			
				_unit_handle = rti.getAttributeHandle( "unit", get_handle() );
				isNotInitialized = false;
			} catch ( FederateNotExecutionMember f ) {
				System.err.println( initErrorMessage + "Federate Not Execution Member" );
				f.printStackTrace();
				return;				
			} catch ( ObjectClassNotDefined i ) {
				System.err.println( initErrorMessage + "Object Class Not Defined" );
				i.printStackTrace();
				return;				
			} catch ( NameNotFound n ) {
				System.err.println( initErrorMessage + "Name Not Found" );
				n.printStackTrace();
				return;				
			} catch ( Exception e ) {
				e.printStackTrace();
				try { Thread.sleep( 50 ); } catch( Exception e1 ) { }					
			}
		}
			
			
		_datamemberNameHandleMap.put( "ObjectRoot.market,market_id", get_market_id_handle() );
		_datamemberNameHandleMap.put( "ObjectRoot.market,period", get_period_handle() );
		_datamemberNameHandleMap.put( "ObjectRoot.market,unit", get_unit_handle() );
			
			
		_datamemberHandleNameMap.put( get_market_id_handle(), "market_id" );
		_datamemberHandleNameMap.put( get_period_handle(), "period" );
		_datamemberHandleNameMap.put( get_unit_handle(), "unit" );
		
	}


	private static boolean _isPublished = false;
	private static String publishErrorMessage = "Error:  ObjectRoot.market:  could not publish:  ";

	/**
	* Publishes the market object class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void publish( RTIambassador rti ) {
		if ( _isPublished ) return;
		
		init( rti );

		
		_publishedAttributeHandleSet.empty();
		for( String attributeName : _publishAttributeNameSet ) {
			try {
				_publishedAttributeHandleSet.add(  _datamemberNameHandleMap.get( "ObjectRoot.market," + attributeName )  );
			} catch ( Exception e ) {
				System.err.println( publishErrorMessage + "Could not publish \"" + attributeName + "\" attribute." );
			}
		}
	

		synchronized( rti ) {
			boolean isNotPublished = true;
			while( isNotPublished ) {
				try {
					rti.publishObjectClass( get_handle(), _publishedAttributeHandleSet );
					isNotPublished = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( publishErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( ObjectClassNotDefined i ) {
					System.err.println( publishErrorMessage + "Object Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isPublished = true;
	}

	private static String unpublishErrorMessage = "Error:  ObjectRoot.market:  could not unpublish:  ";
	/**
	* Unpublishes the market object class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void unpublish( RTIambassador rti ) {
		if ( !_isPublished ) return;
		
		init( rti );
		synchronized( rti ) {
			boolean isNotUnpublished = true;
			while( isNotUnpublished ) {
				try {
					rti.unpublishObjectClass( get_handle() );
					isNotUnpublished = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( unpublishErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( ObjectClassNotDefined i ) {
					System.err.println( unpublishErrorMessage + "Object Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( ObjectClassNotPublished i ) {
					System.err.println( unpublishErrorMessage + "Object Class Not Published" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isPublished = false;
	}

	private static boolean _isSubscribed = false;
	private static String subscribeErrorMessage = "Error:  ObjectRoot.market:  could not subscribe:  ";
	/**
	* Subscribes a federate to the market object class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void subscribe( RTIambassador rti ) {
		if ( _isSubscribed ) return;
		
		init( rti );
		
		_subscribedAttributeHandleSet.empty();
		for( String attributeName : _subscribeAttributeNameSet ) {
			try {
				_subscribedAttributeHandleSet.add(  _datamemberNameHandleMap.get( "ObjectRoot.market," + attributeName )  );
			} catch ( Exception e ) {
				System.err.println( subscribeErrorMessage + "Could not subscribe to \"" + attributeName + "\" attribute." );
			}
		}
	
		
		synchronized( rti ) {
			boolean isNotSubscribed = true;
			while( isNotSubscribed ) {
				try {
					rti.subscribeObjectClassAttributes( get_handle(), _subscribedAttributeHandleSet );
					isNotSubscribed = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( subscribeErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( ObjectClassNotDefined i ) {
					System.err.println( subscribeErrorMessage + "Object Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isSubscribed = true;
	}

	private static String unsubscribeErrorMessage = "Error:  ObjectRoot.market:  could not unsubscribe:  ";
	/**
	* Unsubscribes a federate from the market object class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public static void unsubscribe( RTIambassador rti ) {
		if ( !_isSubscribed ) return;

		init( rti );
		synchronized( rti ) {
			boolean isNotUnsubscribed = true;
			while( isNotUnsubscribed ) {
				try {
					rti.unsubscribeObjectClass( get_handle() );
					isNotUnsubscribed = false;
				} catch ( FederateNotExecutionMember f ) {
					System.err.println( unsubscribeErrorMessage + "Federate Not Execution Member" );
					f.printStackTrace();
					return;
				} catch ( ObjectClassNotDefined i ) {
					System.err.println( unsubscribeErrorMessage + "Object Class Not Defined" );
					i.printStackTrace();
					return;
				} catch ( ObjectClassNotSubscribed i ) {
					System.err.println( unsubscribeErrorMessage + "Object Class Not Subscribed" );
					i.printStackTrace();
					return;
				} catch ( Exception e ) {
					e.printStackTrace();
					try { Thread.sleep( 50 ); } catch( Exception e1 ) { }
				}
			}
		}
		
		_isSubscribed = false;
	}

	/**
	* Return true if "handle" is equal to the handle (RTI assigned) of this class
	* (that is, the market object class).
	*
	* @param handle handle to compare to the value of the handle (RTI assigned) of
	* this class (the market object class).
	* @return "true" if "handle" matches the value of the handle of this class
	* (that is, the market object class).
	*/
	public static boolean match( int handle ) { return handle == get_handle(); }

	/**
	* Returns the handle (RTI assigned) of this instance's object class .
	* 
	* @return the handle (RTI assigned) if this instance's object class
	*/
	public int getClassHandle() { return get_handle(); }

	/**
	* Returns the fully-qualified (dot-delimited) name of this instance's object class.
	* 
	* @return the fully-qualified (dot-delimited) name of this instance's object class
	*/
	public String getClassName() { return get_class_name(); }

	/**
	* Returns the simple name (last name in its fully-qualified dot-delimited name)
	* of this instance's object class.
	* 
	* @return the simple name of this instance's object class 
	*/
	public String getSimpleClassName() { return get_simple_class_name(); }

	/**
	* Returns a set containing the names of all of the non-hiddenattributes of an
	* object class instance.
	*
	* @return set containing the names of all of the attributes of an
	* object class instance
	*/
	public Set< String > getAttributeNames() { return get_attribute_names(); }

	/**
	* Returns a set containing the names of all of the attributes of an
	* object class instance.
	*
	* @return set containing the names of all of the attributes of an
	* object class instance
	*/
	public Set< String > getAllAttributeNames() { return get_all_attribute_names(); }

	/**
	* Publishes the object class of this instance of the class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void publishObject( RTIambassador rti ) { publish( rti ); }

	/**
	* Unpublishes the object class of this instance of this class for a federate.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void unpublishObject( RTIambassador rti ) { unpublish( rti ); }

	/**
	* Subscribes a federate to the object class of this instance of this class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void subscribeObject( RTIambassador rti ) { subscribe( rti ); }

	/**
	* Unsubscribes a federate from the object class of this instance of this class.
	*
	* @param rti handle to the RTI, usu. obtained through the
	* {@link SynchronizedFederate#getRTI()} call
	*/
	public void unsubscribeObject( RTIambassador rti ) { unsubscribe( rti ); }

	
	/**
	* Returns a data structure containing the handles of all attributes for this object
	* class that are currently marked for subscription.  To actually subscribe to these
	* attributes, a federate must call <objectclassname>.subscribe( RTIambassador rti ).
	*
	* @return data structure containing the handles of all attributes for this object
	* class that are currently marked for subscription
	*/
	public AttributeHandleSet getSubscribedAttributeHandleSet() { return _subscribedAttributeHandleSet; }
	

	public String toString() {
		return "market("
			
			
			+ "market_id:" + get_market_id()
			+ "," + "period:" + get_period()
			+ "," + "unit:" + get_unit()
			+ ")";
	}
	



	
	
	/**
	* Publishes the "market_id" attribute of the attribute's containing object
	* class for a federate.
	* Note:  This method only marks the "market_id" attribute for publication.
	* To actually publish the attribute, the federate must (re)publish its containing
	* object class.
	* (using <objectClassName>.publish( RTIambassador rti ) ).
	*/
	public static void publish_market_id() {
		_publishAttributeNameSet.add( "market_id" );
	}

	/**
	* Unpublishes the "market_id" attribute of the attribute's containing object
	* class for a federate.
	* Note:  This method only marks the "market_id" attribute for unpublication.
	* To actually publish the attribute, the federate must (re)publish its containing
	* object class.
	* (using <objectClassName>.publish( RTIambassador rti ) ).
	*/
	public static void unpublish_market_id() {
		_publishAttributeNameSet.remove( "market_id" );
	}
	
	/**
	* Subscribes a federate to the "market_id" attribute of the attribute's
	* containing object class.
	* Note:  This method only marks the "market_id" attribute for subscription.
	* To actually subscribe to the attribute, the federate must (re)subscribe to its
	* containing object class.
	* (using <objectClassName>.subscribe( RTIambassador rti ) ).
	*/
	public static void subscribe_market_id() {
		_subscribeAttributeNameSet.add( "market_id" );
	}

	/**
	* Unsubscribes a federate from the "market_id" attribute of the attribute's
	* containing object class.
	* Note:  This method only marks the "market_id" attribute for unsubscription.
	* To actually unsubscribe to the attribute, the federate must (re)subscribe to its
	* containing object class.
	* (using <objectClassName>.subscribe( RTIambassador rti ) ).
	*/
	public static void unsubscribe_market_id() {
		_subscribeAttributeNameSet.remove( "market_id" );
	}
	
	
	/**
	* Publishes the "period" attribute of the attribute's containing object
	* class for a federate.
	* Note:  This method only marks the "period" attribute for publication.
	* To actually publish the attribute, the federate must (re)publish its containing
	* object class.
	* (using <objectClassName>.publish( RTIambassador rti ) ).
	*/
	public static void publish_period() {
		_publishAttributeNameSet.add( "period" );
	}

	/**
	* Unpublishes the "period" attribute of the attribute's containing object
	* class for a federate.
	* Note:  This method only marks the "period" attribute for unpublication.
	* To actually publish the attribute, the federate must (re)publish its containing
	* object class.
	* (using <objectClassName>.publish( RTIambassador rti ) ).
	*/
	public static void unpublish_period() {
		_publishAttributeNameSet.remove( "period" );
	}
	
	/**
	* Subscribes a federate to the "period" attribute of the attribute's
	* containing object class.
	* Note:  This method only marks the "period" attribute for subscription.
	* To actually subscribe to the attribute, the federate must (re)subscribe to its
	* containing object class.
	* (using <objectClassName>.subscribe( RTIambassador rti ) ).
	*/
	public static void subscribe_period() {
		_subscribeAttributeNameSet.add( "period" );
	}

	/**
	* Unsubscribes a federate from the "period" attribute of the attribute's
	* containing object class.
	* Note:  This method only marks the "period" attribute for unsubscription.
	* To actually unsubscribe to the attribute, the federate must (re)subscribe to its
	* containing object class.
	* (using <objectClassName>.subscribe( RTIambassador rti ) ).
	*/
	public static void unsubscribe_period() {
		_subscribeAttributeNameSet.remove( "period" );
	}
	
	
	/**
	* Publishes the "unit" attribute of the attribute's containing object
	* class for a federate.
	* Note:  This method only marks the "unit" attribute for publication.
	* To actually publish the attribute, the federate must (re)publish its containing
	* object class.
	* (using <objectClassName>.publish( RTIambassador rti ) ).
	*/
	public static void publish_unit() {
		_publishAttributeNameSet.add( "unit" );
	}

	/**
	* Unpublishes the "unit" attribute of the attribute's containing object
	* class for a federate.
	* Note:  This method only marks the "unit" attribute for unpublication.
	* To actually publish the attribute, the federate must (re)publish its containing
	* object class.
	* (using <objectClassName>.publish( RTIambassador rti ) ).
	*/
	public static void unpublish_unit() {
		_publishAttributeNameSet.remove( "unit" );
	}
	
	/**
	* Subscribes a federate to the "unit" attribute of the attribute's
	* containing object class.
	* Note:  This method only marks the "unit" attribute for subscription.
	* To actually subscribe to the attribute, the federate must (re)subscribe to its
	* containing object class.
	* (using <objectClassName>.subscribe( RTIambassador rti ) ).
	*/
	public static void subscribe_unit() {
		_subscribeAttributeNameSet.add( "unit" );
	}

	/**
	* Unsubscribes a federate from the "unit" attribute of the attribute's
	* containing object class.
	* Note:  This method only marks the "unit" attribute for unsubscription.
	* To actually unsubscribe to the attribute, the federate must (re)subscribe to its
	* containing object class.
	* (using <objectClassName>.subscribe( RTIambassador rti ) ).
	*/
	public static void unsubscribe_unit() {
		_subscribeAttributeNameSet.remove( "unit" );
	}
	

	
	
	private Attribute< Long > _market_id =
 		new Attribute< Long >(  new Long( 0 )  );
	
	/**
	* Set the value of the "market_id" attribute to "value" for this object.
	*
	* @param value the new value for the "market_id" attribute
	*/
	public void set_market_id( long value ) {
		_market_id.setValue( value );
		_market_id.setTime( getTime() );
	}
	
	/**
	* Returns the value of the "market_id" attribute of this object.
	*
	* @return the value of the "market_id" attribute
	*/
	public long get_market_id() {
		return _market_id.getValue();
	}
	
	/**
	* Returns the current timestamp of the "market_id" attribute of this object.
	* 
	* @return the current timestamp of the "market_id" attribute
	*/
	public double get_market_id_time() {
		return _market_id.getTime();
	}
	
	
	private Attribute< Integer > _period =
 		new Attribute< Integer >(  new Integer( 0 )  );
	
	/**
	* Set the value of the "period" attribute to "value" for this object.
	*
	* @param value the new value for the "period" attribute
	*/
	public void set_period( int value ) {
		_period.setValue( value );
		_period.setTime( getTime() );
	}
	
	/**
	* Returns the value of the "period" attribute of this object.
	*
	* @return the value of the "period" attribute
	*/
	public int get_period() {
		return _period.getValue();
	}
	
	/**
	* Returns the current timestamp of the "period" attribute of this object.
	* 
	* @return the current timestamp of the "period" attribute
	*/
	public double get_period_time() {
		return _period.getTime();
	}
	
	
	private Attribute< String > _unit =
 		new Attribute< String >(  new String( "" )  );
	
	/**
	* Set the value of the "unit" attribute to "value" for this object.
	*
	* @param value the new value for the "unit" attribute
	*/
	public void set_unit( String value ) {
		_unit.setValue( value );
		_unit.setTime( getTime() );
	}
	
	/**
	* Returns the value of the "unit" attribute of this object.
	*
	* @return the value of the "unit" attribute
	*/
	public String get_unit() {
		return _unit.getValue();
	}
	
	/**
	* Returns the current timestamp of the "unit" attribute of this object.
	* 
	* @return the current timestamp of the "unit" attribute
	*/
	public double get_unit_time() {
		return _unit.getTime();
	}
	


	protected market( ReflectedAttributes datamemberMap, boolean initFlag ) {
		super( datamemberMap, false );
		if ( initFlag ) setAttributes( datamemberMap );
	}
	
	protected market( ReflectedAttributes datamemberMap, LogicalTime logicalTime, boolean initFlag ) {
		super( datamemberMap, logicalTime, false );
		if ( initFlag ) setAttributes( datamemberMap );
	}


	/**
	* Creates an instance of the market object class, using
	* "datamemberMap" to initialize its attribute values.
	* "datamemberMap" is usually acquired as an argument to an RTI federate
	* callback method, such as "receiveInteraction".
	*
	* @param datamemberMap data structure containing initial values for the
	* attributes of this new market object class instance
	*/
	public market( ReflectedAttributes datamemberMap ) {
		this( datamemberMap, true );
	}
	
	/**
	* Like {@link #market( ReflectedAttributes datamemberMap )}, except this
	* new market object class instance is given a timestamp of
	* "logicalTime".
	*
	* @param datamemberMap data structure containing initial values for the
	* attributes of this new market object class instance
	* @param logicalTime timestamp for this new market object class
	* instance
	*/
	public market( ReflectedAttributes datamemberMap, LogicalTime logicalTime ) {
		this( datamemberMap, logicalTime, true );
	}

	/**
	* Creates a new market object class instance that is a duplicate
	* of the instance referred to by market_var.
	*
	* @param market_var market object class instance of which
	* this newly created market object class instance will be a
	* duplicate
	*/
	public market( market market_var ) {
		super( market_var );
		
		
		set_market_id( market_var.get_market_id() );
		set_period( market_var.get_period() );
		set_unit( market_var.get_unit() );
	}


	/**
	* Returns the value of the attribute whose name is "datamemberName"
	* for this object.
	*
	* @param datamemberName name of attribute whose value is to be
	* returned
	* @return value of the attribute whose name is "datamemberName"
	* for this object
	*/
	public Object getAttribute( String datamemberName ) {
		
		
		
		if (  "market_id".equals( datamemberName )  ) return new Long( get_market_id() );
		else if (  "period".equals( datamemberName )  ) return new Integer( get_period() );
		else if (  "unit".equals( datamemberName )  ) return get_unit();
		else return super.getAttribute( datamemberName );
	}
	
	/**
	* Returns the value of the attribute whose handle (RTI assigned)
	* is "datamemberHandle" for this object.
	*
	* @param datamemberHandle handle (RTI assigned) of attribute whose
	* value is to be returned
	* @return value of the attribute whose handle (RTI assigned) is
	* "datamemberHandle" for this object
	*/
	public Object getAttribute( int datamemberHandle ) {
		
				
		
		if ( get_market_id_handle() == datamemberHandle ) return new Long( get_market_id() );
		else if ( get_period_handle() == datamemberHandle ) return new Integer( get_period() );
		else if ( get_unit_handle() == datamemberHandle ) return get_unit();
		else return super.getAttribute( datamemberHandle );
	}
	
	protected boolean setAttributeAux( int param_handle, String val ) {
		boolean retval = true;		
		
			
		
		if ( param_handle == get_market_id_handle() ) set_market_id( Long.parseLong( val ) );
		else if ( param_handle == get_period_handle() ) set_period( Integer.parseInt( val ) );
		else if ( param_handle == get_unit_handle() ) set_unit( val );
		else retval = super.setAttributeAux( param_handle, val );
		
		return retval;
	}
	
	protected boolean setAttributeAux( String datamemberName, String val ) {
		boolean retval = true;
		
			
		
		if (  "market_id".equals( datamemberName )  ) set_market_id( Long.parseLong( val ) );
		else if (  "period".equals( datamemberName )  ) set_period( Integer.parseInt( val ) );
		else if (  "unit".equals( datamemberName )  ) set_unit( val );	
		else retval = super.setAttributeAux( datamemberName, val );
		
		return retval;
	}
	
	protected boolean setAttributeAux( String datamemberName, Object val ) {
		boolean retval = true;
		
		
		
		if (  "market_id".equals( datamemberName )  ) set_market_id( (Long)val );
		else if (  "period".equals( datamemberName )  ) set_period( (Integer)val );
		else if (  "unit".equals( datamemberName )  ) set_unit( (String)val );		
		else retval = super.setAttributeAux( datamemberName, val );
		
		return retval;
	}

	protected SuppliedAttributes createSuppliedDatamembers( boolean force ) {
		SuppliedAttributes datamembers = super.createSuppliedDatamembers( force );

	
		boolean isPublished = false;
		
		
			try {
				isPublished = _publishedAttributeHandleSet.isMember( get_market_id_handle() );
			} catch ( Exception e ) {
				System.err.println( "ERROR:  ObjectRoot.market.createSuppliedAttributes:  could not determine if market_id is published." );
				isPublished = false;
			}
			if (  isPublished && _market_id.shouldBeUpdated( force )  ) {
				datamembers.add( get_market_id_handle(), Long.toString( get_market_id() ).getBytes() );
				_market_id.setHasBeenUpdated();
			}
			try {
				isPublished = _publishedAttributeHandleSet.isMember( get_period_handle() );
			} catch ( Exception e ) {
				System.err.println( "ERROR:  ObjectRoot.market.createSuppliedAttributes:  could not determine if period is published." );
				isPublished = false;
			}
			if (  isPublished && _period.shouldBeUpdated( force )  ) {
				datamembers.add( get_period_handle(), Integer.toString( get_period() ).getBytes() );
				_period.setHasBeenUpdated();
			}
			try {
				isPublished = _publishedAttributeHandleSet.isMember( get_unit_handle() );
			} catch ( Exception e ) {
				System.err.println( "ERROR:  ObjectRoot.market.createSuppliedAttributes:  could not determine if unit is published." );
				isPublished = false;
			}
			if (  isPublished && _unit.shouldBeUpdated( force )  ) {
				datamembers.add( get_unit_handle(), get_unit().getBytes() );
				_unit.setHasBeenUpdated();
			}
	
		return datamembers;
	}

	
	public void copyFrom( Object object ) {
		super.copyFrom( object );
		if ( object instanceof market ) {
			market data = (market)object;
			
			
				_market_id = data._market_id;
				_period = data._period;
				_unit = data._unit;
			
		}
	}
}
